name: SPARQ (Windows)

on:
  push:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: >
          cmake -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SPARQ_windows
          path: |
            build/src/SPARQ.exe
            build/src/assets/**
            build/src/imgui.ini
            build/src/config.ini
            README.md
            FORMAT.md