name: SPARQ (Windows)

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:


jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        submodules: 'true'

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: MINGW64
        update: true
        upgrade: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
    - name: Check g++ version
      run: g++ --version
    - name: Check g++ location
      run: where.exe g++

    - name: Build project
      working-directory: ./src
      run: |
        make release=1
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: SPARQ_windows
        path: |
            ./src/assets/
            ./src/SPARQ.exe
            ./src/imgui.ini
            ./README.md
            ./FORMAT.md